pipeline {
    agent any

    stages {
        stage('Checkout Code (SSH)') {
            steps {
                git branch: 'main',
                  credentialsId: 'github3-ssh-key',
                    url: 'git@github.com:disha-cyber/agentic-ai'
            }
        }

        stage('Verify') {
            steps {
                sh 'ls -la'
            }
        }
        
    }
}